version: "3.9"

services:
  api:
    image: strapi/strapi
    volumes:
      - ../.:/srv/app
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
    ports:
      - 1337:1337
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: wongames
      POSTGRES_USER: wongames
      POSTGRES_PASSWORD: wongames123
    ports:
      - 5432:5432
